#!/bin/sh

if [ ! -f ./aws/config ]; then
    echo FATAL missing ./aws/config file. You can use ./aws/config.tmpl to generate one
    exit 1
fi

export tag=latest
if [ "$1" != "" ]; then
    export tag=$1
fi

if [ "$2" != "no-build" ]; then
    docker build -t "shopify_serverless_app:${tag}" .
fi

docker run -it \
    -v "${PWD}"/app:/app \
    -v "${PWD}/aws:/root/.aws" \
    "shopify_serverless_app:${tag}" \
    bash

